### ISSUE TITLE
Feature request: module autocompletion

### ISSUE THREAD

**Issue by JonathanWilbur** [korekontrol/vscode-saltstack#2]
I don't think it would be too hard to add autocompletion, such that, when I type, say, `file.`, I get a dropdown that contains `exists`, `managed`, `symlink`, etc. This could also be implemented as snippets instead.

**Comment by marek-obuchowicz** [comment]
That would be nice, I agree. This requires implementing LanguageServer and somehow integrating with saltstack (probably in a way similiar to `salt-lint`) in order to extract state names. Seems like a task currently to heavy for me - i would be happy to look into it if you could provide some language server examples, that could serve as base for this implementation.

**Comment by marek-obuchowicz** [comment]
Implemented in #6
